/*
 * This file is generated by jOOQ.
 */
package ca.ultracrepidarianism.kingdom.model.test.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PlayersPermissionlevel implements EnumType {

    MEMBER("MEMBER"),

    OFFICER("OFFICER"),

    OWNER("OWNER");

    private final String literal;

    private PlayersPermissionlevel(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return null;
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static PlayersPermissionlevel lookupLiteral(String literal) {
        return EnumType.lookupLiteral(PlayersPermissionlevel.class, literal);
    }
}
