/*
 * This file is generated by jOOQ.
 */
package ca.ultracrepidarianism.kingdom.model.test;


import ca.ultracrepidarianism.kingdom.model.test.tables.Claims;
import ca.ultracrepidarianism.kingdom.model.test.tables.Kingdoms;
import ca.ultracrepidarianism.kingdom.model.test.tables.Players;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Minecraft extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>minecraft</code>
     */
    public static final Minecraft MINECRAFT = new Minecraft();

    /**
     * The table <code>minecraft.claims</code>.
     */
    public final Claims CLAIMS = Claims.CLAIMS;

    /**
     * The table <code>minecraft.kingdoms</code>.
     */
    public final Kingdoms KINGDOMS = Kingdoms.KINGDOMS;

    /**
     * The table <code>minecraft.players</code>.
     */
    public final Players PLAYERS = Players.PLAYERS;

    /**
     * No further instances allowed
     */
    private Minecraft() {
        super("minecraft", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Claims.CLAIMS,
            Kingdoms.KINGDOMS,
            Players.PLAYERS
        );
    }
}
