/*
 * This file is generated by jOOQ.
 */
package ca.ultracrepidarianism.kingdom.model.test;


import ca.ultracrepidarianism.kingdom.model.test.tables.Claims;
import ca.ultracrepidarianism.kingdom.model.test.tables.Kingdoms;
import ca.ultracrepidarianism.kingdom.model.test.tables.Players;


/**
 * Convenience access to all tables in minecraft.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>minecraft.claims</code>.
     */
    public static final Claims CLAIMS = Claims.CLAIMS;

    /**
     * The table <code>minecraft.kingdoms</code>.
     */
    public static final Kingdoms KINGDOMS = Kingdoms.KINGDOMS;

    /**
     * The table <code>minecraft.players</code>.
     */
    public static final Players PLAYERS = Players.PLAYERS;
}
