/*
 * This file is generated by jOOQ.
 */
package ca.ultracrepidarianism.kingdom.model.test.tables.records;


import ca.ultracrepidarianism.kingdom.model.test.tables.Claims;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClaimsRecord extends UpdatableRecordImpl<ClaimsRecord> implements Record5<Long, String, Integer, Integer, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>minecraft.claims.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>minecraft.claims.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>minecraft.claims.world</code>.
     */
    public void setWorld(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>minecraft.claims.world</code>.
     */
    public String getWorld() {
        return (String) get(1);
    }

    /**
     * Setter for <code>minecraft.claims.x</code>.
     */
    public void setX(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>minecraft.claims.x</code>.
     */
    public Integer getX() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>minecraft.claims.z</code>.
     */
    public void setZ(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>minecraft.claims.z</code>.
     */
    public Integer getZ() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>minecraft.claims.kingdomId</code>.
     */
    public void setKingdomid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>minecraft.claims.kingdomId</code>.
     */
    public Long getKingdomid() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, Integer, Integer, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, String, Integer, Integer, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Claims.CLAIMS.ID;
    }

    @Override
    public Field<String> field2() {
        return Claims.CLAIMS.WORLD;
    }

    @Override
    public Field<Integer> field3() {
        return Claims.CLAIMS.X;
    }

    @Override
    public Field<Integer> field4() {
        return Claims.CLAIMS.Z;
    }

    @Override
    public Field<Long> field5() {
        return Claims.CLAIMS.KINGDOMID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getWorld();
    }

    @Override
    public Integer component3() {
        return getX();
    }

    @Override
    public Integer component4() {
        return getZ();
    }

    @Override
    public Long component5() {
        return getKingdomid();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getWorld();
    }

    @Override
    public Integer value3() {
        return getX();
    }

    @Override
    public Integer value4() {
        return getZ();
    }

    @Override
    public Long value5() {
        return getKingdomid();
    }

    @Override
    public ClaimsRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ClaimsRecord value2(String value) {
        setWorld(value);
        return this;
    }

    @Override
    public ClaimsRecord value3(Integer value) {
        setX(value);
        return this;
    }

    @Override
    public ClaimsRecord value4(Integer value) {
        setZ(value);
        return this;
    }

    @Override
    public ClaimsRecord value5(Long value) {
        setKingdomid(value);
        return this;
    }

    @Override
    public ClaimsRecord values(Long value1, String value2, Integer value3, Integer value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClaimsRecord
     */
    public ClaimsRecord() {
        super(Claims.CLAIMS);
    }

    /**
     * Create a detached, initialised ClaimsRecord
     */
    public ClaimsRecord(Long id, String world, Integer x, Integer z, Long kingdomid) {
        super(Claims.CLAIMS);

        setId(id);
        setWorld(world);
        setX(x);
        setZ(z);
        setKingdomid(kingdomid);
        resetChangedOnNotNull();
    }
}
