name: Package Plugin Jar

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DserverPluginPath=.

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Create Release Draft
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.1  # Specify the desired tag name for the release
        release_name: Release 0.0.1  # Specify the desired release name
        draft: true  # Set this to 'true' to create a release draft
        body: |  # Add release notes or description
          Release notes go here.
          You can provide more details about the release.

    - name: Attach Maven Package
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar  # Specify the path to the Maven package you want to attach
        tag_name: v1.0.0  # Specify the same tag name used for the release

    - name: Get Release ID
      id: get_release
      run: echo "Release ID: ${{ steps.create_release.outputs.id }}"
